[versions]
agp = "8.3.1"
kotlin = "2.0.0"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
retrofit2 = "2.11.0"
glide = "4.16.0"
okhttp3 = "4.9.0"
fragmentKtx = "1.5.2"
hilt = "2.51.1"
ksp = "2.0.0-1.0.24"
room = "2.6.1"
jetbrainsKotlinJvm = "1.9.24"
coroutine = "1.8.1"
androidxComposeBom = "2024.06.00"
androidxComposeNavigation = "2.7.7"
androidxComposeMaterial3 = "1.3.0-rc01"
hiltNavigationCompose = "1.2.0"
kotlinxImmutable = "0.3.7"

# https://github.com/skydoves/landscapist
landscapist = "2.3.4"

# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidxLifecycle = "2.8.4"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx"}
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
retrofit2-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit2"}
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit2" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide"}
glideCompiler = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }

kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

aac-room = { module = "androidx.room:room-runtime", version.ref = "room" }
aac-roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
aac-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

#okhttp3-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

landscapist-bom = { group = "com.github.skydoves", name = "landscapist-bom", version.ref = "landscapist" }
landscapist-coil = { group = "com.github.skydoves", name = "landscapist-coil" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }



[bundles]
retrofit2 = [
    "retrofit2-core",
    "retrofit2-converter-gson",
    "okhttp3-logging-interceptor"
]

